apiVersion: v1
kind: Namespace
metadata:
  name: npm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy-manager
  namespace: npm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy-manager
  template:
    metadata:
      labels:
        app: nginx-proxy-manager
    spec:
      hostNetwork: true
      containers:
        - name: nginx-proxy-manager
          image: jc21/nginx-proxy-manager:latest
          ports:
            - containerPort: 80
            - containerPort: 81
            - containerPort: 443
          volumeMounts:
            - name: npm-data
              mountPath: /data
            - name: npm-letsencrypt
              mountPath: /etc/letsencrypt
      volumes:
        - name: npm-data
          persistentVolumeClaim:
            claimName: npm-data-pvc
        - name: npm-letsencrypt
          persistentVolumeClaim:
            claimName: npm-letsencrypt-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: npm-data-pvc
  namespace: npm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: npm-letsencrypt-pvc
  namespace: npm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi